### ISSUE TITLE
Wrong columns parsed

### ISSUE THREAD

**Issue by Mokapon** [KnowledgeFlows/ui-fm-metadata-to-json#1]
I used the [attached csv file](https://github.com/KnowledgeFlows/ui-fm-metadata-to-json/files/212543/fm_meta.txt) which corresponds to the latest version of the metadata (its extension is .txt because github would not accept .csv): 

In the obtained JSON several attributes are apparently not linked to the correct columns:

* shortDescription contains only "y", probably the content of the 'visible' column
* 'logo' contains the contents of "phrase"
* 'questionable' those of 'displayIfSelected'
* etc.

All columns passed the first 3 seem to be wrong (I changed their order in the excel file since last time).

**Comment by surli** [comment]
Fix with the last commit. Be careful to not change the column names ;)
